version: "2"

services:
  pininja:
    build: .
    container_name: pininja-gatsby
    restart: always
    volumes:
      - "./src:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    environment:
      - VIRTUAL_HOST=3.14159.ninja
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=3.14159.ninja
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: arthur_default
