version: "2"

services:
  pininja:
    build: .
    container_name: pininja-gatsby
    restart: always
    environment:
      - VIRTUAL_HOST=3.14159.ninja,arthurdev.duckdns.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=3.14159.ninja,arthurdev.duckdns.org
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: arthur_default
